=== mishokopchev/FMI-c-/asp-dota/XML/dota.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT dota (game, buildings, heroes, items) >
<!ELEMENT game (name, genre, designer) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT genre (#PCDATA) >
<!ELEMENT designer (#PCDATA) >
<!ELEMENT buildings (building+) >
<!ELEMENT building (region, type, life, defence, damage) >
<!ATTLIST building 
    side (sentinel|scorge) #REQUIRED
    main CDATA #REQUIRED >
<!ELEMENT region (#PCDATA) >
<!ELEMENT type (#PCDATA) >
<!ELEMENT life (#PCDATA) >
<!ELEMENT defence (#PCDATA) >
<!ELEMENT damage (#PCDATA) >
<!ELEMENT heroes (hero+) >
<!ELEMENT hero (title, atribute, status,movespeed, skills, armor, dps) >
<!ATTLIST hero
    id ID #REQUIRED
    attack (range|melee) #REQUIRED
    affiliation (sentinel|scorge) #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT atribute (#PCDATA) >
<!ATTLIST atribute
    short (AGI|INT|STR) #REQUIRED>
<!ELEMENT status (#PCDATA) >
<!ELEMENT movespeed (#PCDATA) >
<!ELEMENT skills (skill+) >
<!ELEMENT skill (num1, num2, num3, num4) >
<!ELEMENT num1 (#PCDATA)>
<!ELEMENT num2 (#PCDATA)>
<!ELEMENT num3 (#PCDATA)>
<!ELEMENT num4 (#PCDATA)>
<!ELEMENT armor (#PCDATA) >
<!ELEMENT dps (#PCDATA) >
<!ELEMENT items (item+) >
<!ELEMENT item (merchant, price, effects, need, description) >
<!ATTLIST item 
    id CDATA #REQUIRED
    slot (1|2|3|4|5|6) #REQUIRED
    hero CDATA #REQUIRED>
<!ELEMENT merchant (#PCDATA) >
<!ELEMENT price (#PCDATA) >
<!ELEMENT effects (effect+) >
<!ELEMENT effect (main, secondary) >
<!ELEMENT main (#PCDATA) >
<!ELEMENT secondary (#PCDATA) >
<!ELEMENT need (#PCDATA) >
<!ELEMENT description (#PCDATA) >

=== mishokopchev/FMI-c-/asp-dota/XML/valid_xml_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dota SYSTEM "dota.dtd">
<dota>
    <game>
        <name> Defense of the Ancients ( Дота )</name>
        <genre> Multiplayer online battle arena ( или бойна арена с повече от един играча ) </genre>
        <designer> "Ice Frog" </designer>
    </game>
    <buildings>
        <building side="sentinel" main="Tree of Life">
            <region> средата </region>
            <type> кула </type>
            <life> 1000</life>
            <defence> 2 </defence>
            <damage> 40 </damage>
        </building>
        <building side="scorge" main="Tree of Life">
            <region> средата </region>
            <type> кула </type>
            <life> 1200</life>
            <defence> 3 </defence>
            <damage> 60 </damage>
        </building>
        <building side="scorge" main="Acolyte">
            <region> горен ръкав </region>
            <type> казарма </type>
            <life> 2300 </life>
            <defence> 3.5 </defence>
            <damage> няма </damage>
        </building>
    </buildings>
    
    <heroes>
        <hero id="Tuskarr" attack="melee" affiliation="sentinel">
            <title> Ymir </title> 
            <atribute short="STR"> сила </atribute>
            <status> регенерация </status>
            <movespeed> Скорост на движение: 305 </movespeed>
            <skills>
                <skill>
                    <num1> Ice Shards   </num1>
                    <num2> Snowball   </num2>
                    <num3> Frozen Sigil  </num3>
                    <num4> Walrus Punch  </num4>
                </skill>
            </skills>
            <armor> броня: 3.22 </armor>
            <dps> щета: 50 - 54 </dps>
        </hero>  
        <hero id="Axe" attack="melee" affiliation="scorge">
            <title> Mogul Khan </title> 
            <atribute short="STR"> сила </atribute>
            <status> няма </status>
            <movespeed> Скорост на движение: 290 </movespeed>
            <skills>
                <skill>
                    <num1> Berserker's Call   </num1>
                    <num2> Battle Hunger   </num2>
                    <num3> Counter Helix  </num3>
                    <num4> Culling Blade  </num4>
                </skill>
            </skills>
            <armor> броня: 1.8 </armor>
            <dps> щета: 49 - 53 </dps>
        </hero>  
        <hero id="Crixalis" attack="melee" affiliation="scorge">
            <title> Sand King </title> 
            <atribute short="AGI"> ловкост  </atribute>
            <status> илюзии </status>
            <movespeed> Скорост на движение: 300 </movespeed>
            <skills>
                <skill>
                    <num1> Burrowstrike   </num1>
                    <num2> Sand Storm </num2>
                    <num3> Caustic Finale   </num3>
                    <num4> Epicenter   </num4>
                </skill>
            </skills>
            <armor> броня: 2.66 </armor>
            <dps> щета: 43 - 59 </dps>
        </hero>  
    </heroes>
    
    <items>
        <item id="Satanic " slot="2" hero="Tuskarr">
            <merchant> Enchanted Artifacts </merchant>
            <price> 6150 </price>
            <effects> 
                <effect>
                    <main> 25 сила, 20 щета, 5 броня </main>
                    <secondary>Крадене на живот (пасивно), Нечовшка ярост (активно) </secondary>
                </effect>
            </effects>
            <need> Секира (3200) , Каска на доминацията (1850)  </need>
            <description> Мощно оръжие, казва се , че са били притежавани от самите Drak'thul. </description>
        </item>
        <item id="Bracer" slot="6" hero="Crixalis">
            <merchant> Gateway Relics </merchant>
            <price> 525 </price>
            <effects> 
                <effect>
                    <main> 6 сила  </main>
                    <secondary> 3 щета </secondary>
                </effect>
            </effects>
            <need> корона на благородството (185), рицърска ръкавица на силата (150)   </need>
            <description> Украсена гривна за китката. </description>
        </item>
    </items>
    
</dota>

=== mishokopchev/FMI-c-/asp-dota/XML/valid_xml_7.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dota SYSTEM "dota.dtd">
<dota>
  <game>
    <name>dwqdqw</name>
    <genre>dqwdqw</genre>
    <designer>dqwdwq</designer>
  </game>
  <buildings>
    <building side="scorge" main="main">
      <region>region</region>
      <type>building</type>
      <life>1</life>
      <defence>123</defence>
      <damage>1</damage>
    </building>
    <building side="scorge" main="main">
      <region>region</region>
      <type>building</type>
      <life>1</life>
      <defence>123</defence>
      <damage>1</damage>
    </building>
  </buildings>
  <heroes>
    <hero attack="melee" affiliation="scorge">
      <title>titole</title>
      <atribute short="AGI" />
      <status>status</status>
      <movespeed>123</movespeed>
      <skills />
      <armor>kur</armor>
      <dps>123</dps>
    </hero>
    <hero attack="melee" affiliation="scorge">
      <title>titole</title>
      <atribute short="AGI" />
      <status>status</status>
      <movespeed>123</movespeed>
      <skills />
      <armor>kur</armor>
      <dps>123</dps>
    </hero>
  </heroes>
  <items>
    <item slot="0" hero="kur">
      <merchant>qk</merchant>
      <price>123</price>
      <effects>
        <effect>
          <main>dobre</main>
          <secondary>qko da</secondary>
        </effect>
        <effect>
          <main>dobre</main>
          <secondary>qko da</secondary>
        </effect>
      </effects>
      <need>tes</need>
      <description>da</description>
    </item>
    <item slot="0" hero="kur">
      <merchant>qk</merchant>
      <price>123</price>
      <effects>
        <effect>
          <main>dobre</main>
          <secondary>qko da</secondary>
        </effect>
        <effect>
          <main>dobre</main>
          <secondary>qko da</secondary>
        </effect>
      </effects>
      <need>tes</need>
      <description>da</description>
    </item>
  </items>
</dota>

=== mishokopchev/FMI-c-/asp-dota/XML/valid_xml_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dota SYSTEM "dota.dtd">
<dota>   
    <game>
        <name> Defense of the Ancients ( Дота )</name>
        <genre> Multiplayer online battle arena ( или бойна арена с повече от един играча ) </genre>
        <designer> "Ice Frog" </designer>
    </game>   
    <buildings>
        <building side="sentinel" main="Tree of Life">
            <region> средата </region>
            <type> къщичка </type>
            <life> 1000</life>
            <defence> 2 </defence>
            <damage> няма </damage>
        </building>
        <building side="scorge" main="Acolyte">
            <region> средата </region>
            <type> главна сграда </type>
            <life> 10000 </life>
            <defence> 3 </defence>
            <damage> няма </damage>
        </building>
    </buildings>
    
    <heroes>
        <hero id="Earthshaker" attack="melee" affiliation="sentinel">
            <title> Raigor Stonehoof </title> 
            <atribute short="STR"> сила </atribute>
            <status> двойна щета </status>
            <movespeed> Скорост на движение: 310 </movespeed>
            <skills>
                <skill>
                    <num1> Fissure  </num1>
                    <num2> Enchant Totem  </num2>
                    <num3> Aftershock  </num3>
                    <num4> Echo Slams </num4>
                </skill>
            </skills>
            <armor> Броня: 2.68 </armor>
            <dps> Щета: 46 - 56 </dps>
        </hero>  
        <hero id="Oblivion" attack="range" affiliation="scorge">
            <title> Pugna </title> 
            <atribute short="INT"> интелигентност </atribute>
            <status> няма </status>
            <movespeed> Скорост на движение: 320 </movespeed>
            <skills>
                <skill>
                    <num1> Nether Blast  </num1>
                    <num2> Decrepify  </num2>
                    <num3> Nether Ward  </num3>
                    <num4> Life Drain </num4>
                </skill>
            </skills>
            <armor> Броня: 1.54 </armor>
            <dps> Щета: 41 - 49 </dps>
        </hero>  
        <hero id="Zet" attack="range" affiliation="scorge">
            <title> Arc Warden </title> 
            <atribute short="AGI"> ловкост  </atribute>
            <status> бързане </status>
            <movespeed> Скорост на движение: 295 </movespeed>
            <skills>
                <skill>
                    <num1> Flux  </num1>
                    <num2> Magnetic Field </num2>
                    <num3> Spark Wraith  </num3>
                    <num4> Tempest двойна  </num4>
                </skill>
            </skills>
            <armor> Броня: 0.1 </armor>
            <dps> Щета: 40-50 </dps>
        </hero>  
    </heroes>
    
    <items>
        <item id="Aghanim's Scepter" slot="2" hero="Earthshaker">
            <merchant> Arcane Sanctum </merchant>
            <price> 4200 </price>
            <effects> 
                <effect>
                    <main> 10 всички атрибути, 200 живот, 150 мана </main>
                    <secondary> Подобравяне на ултимата (пасивно) </secondary>
                </effect>
            </effects>
            <need> Пойнт Бустер (1200), Брадва на Огре (1000), Острие на готовността (1000), Жезъл на магиосник (1000) </need>
            <description> Жезъл на магьосник със сила на полубог. </description>
        </item>
        <item id="Empty Bottle" slot="1" hero="Zet">
            <merchant> Ancient of Wonders </merchant>
            <price> 650 </price>
            <effects> 
                <effect>
                    <main> Регенерация (активно) </main>
                    <secondary> Хващане на руни (активно) </secondary>
                </effect>
            </effects>
            <need> няма </need>
            <description> Вълшебна бутилка, която е оцеляла през вековете. Тя може да съхранява лековита вода и руни. </description>
        </item>
    </items>
    
</dota>

=== mishokopchev/FMI-c-/asp-dota/XML/valid_xml_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dota SYSTEM "dota.dtd">
<dota>
    
    <game>
        <name> Defense of the Ancients ( Дота )</name>
        <genre> Multiplayer online battle arena ( или бойна арена с повече от един играча ) </genre>
        <designer> "Ice Frog" </designer>
    </game>
    
    <buildings>
        <building side="scorge" main="Acolyte" >
            <region> долен ръкав </region>
            <type> казарма </type>
            <life> 2000 </life>
            <defence> 3 </defence>
            <damage> няма </damage>
        </building>
        <building side="sentinel" main="Tree of Life">
            <region> горен ръкав </region>
            <type> казарма </type>
            <life> 2500 </life>
            <defence> 3 </defence>
            <damage> няма </damage>
        </building>
    </buildings>
    
    <heroes>
        <hero id="Phoenix" attack="range" affiliation="sentinel">
            <title> Icarus </title> 
            <atribute short="STR"> сила </atribute>
            <status> двойна щета  </status>
            <movespeed> Скорост на движение: 285 </movespeed>
            <skills>
                <skill>
                    <num1> Icarus Dive  </num1>
                    <num2> Fire Spirits  </num2>
                    <num3> Sun Ray  </num3>
                    <num4> Supernova  </num4>
                </skill>
            </skills>
            <armor> броня: -0.32 </armor>
            <dps> щета: 43-53 </dps>
        </hero>  
        <hero id="Spiritbreaker" attack="melee" affiliation="scorge">
            <title> Barathrum </title> 
            <atribute short="STR"> сила </atribute>
            <status> няма </status>
            <movespeed> Скорост на движение: 290 </movespeed>
            <skills>
                <skill>
                    <num1> Charge of Darkness  </num1>
                    <num2> Empowering бързане  </num2>
                    <num3> Greater Bash  </num3>
                    <num4> Nether Strike  </num4>
                </skill>
            </skills>
            <armor> броня: 5.38 </armor>
            <dps> щета: 60-70 </dps>
        </hero>  
        <hero id="Undying" attack="melee" affiliation="scorge">
            <title> Dirge </title> 
            <atribute short="STR"> сила </atribute>
            <status> няма </status>
            <movespeed> Скорост на движение: 310 </movespeed>
            <skills>
                <skill>
                    <num1> Decay  </num1>
                    <num2> Soul Rip  </num2>
                    <num3> Tombstone  </num3>
                    <num4> Flesh Golem  </num4>
                </skill>
            </skills>
            <armor> броня: 3.4 </armor>
            <dps> щета: 57 - 65 </dps>
        </hero>  
        <hero id="Butcher" attack="melee" affiliation="scorge">
            <title> Pudge </title> 
            <atribute short="STR"> сила </atribute>
            <status> няма  </status>
            <movespeed> Скорост на движение: 285 </movespeed>
            <skills>
                <skill>
                    <num1> Meat Hook  </num1>
                    <num2> Rot  </num2>
                    <num3> Flesh Heap  </num3>
                    <num4> Flesh Heap  </num4>
                </skill>
            </skills>
            <armor> броня: 0.96 </armor>
            <dps> щета: 52 - 58 </dps>
        </hero>  
    </heroes>
    
    <items>
        <item id="Mask of Madness" slot="1" hero="Butcher">
            <merchant> Enchanted Artifacts </merchant>
            <price> 1900 </price>
            <effects> 
                <effect>
                    <main> Крадене на живот (пасивно) </main>
                    <secondary> Берзерк (активно) </secondary>
                </effect>
            </effects>
            <need> Маска на смъртта (900) </need>
            <description> Тази маска изглежда толкова странно, че ви тласка към лудост. </description>
        </item>
        <item id="Blade Mail" slot="2" hero="Undying">
            <merchant> Protectorate </merchant>
            <price> 2200 </price>
            <effects> 
                <effect>
                    <main> 22 щета, 6 броня </main>
                    <secondary> връща щета (активно) </secondary>
                </effect>
            </effects>
            <need> Меч (1200), Броня (550), Наметало на магиосник  (450)  </need>
            <description> Изключително точна броня, изобретен от Пламтящия легион </description>
        </item>
    </items>
    
</dota>

=== mishokopchev/FMI-c-/asp-dota/XML/generated.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dota SYSTEM "dota.dtd">
<dota>
  <game>
    <name>dwqdqw</name>
    <genre>dqwdqw</genre>
    <designer>dqwdwq</designer>
  </game>
  <buildings>
    <building side="scorge" main="main">
      <region>region</region>
      <type>type</type>
      <life>100</life>
      <defence>123</defence>
      <damage>100</damage>
    </building>
    <building side="scorge" main="main">
      <region>region</region>
      <type>type</type>
      <life>100</life>
      <defence>123</defence>
      <damage>100</damage>
    </building>
  </buildings>
  <heroes>
    <hero id="EarthDick" attack="melee" affiliation="scorge">
      <title>wqq</title>
      <atribute short="AGI" />
      <status>21</status>
      <movespeed>2</movespeed>
      <skills>
        <skill>
          <num1>ewq</num1>
          <num2>dqwdqw</num2>
          <num3>dqwdqw</num3>
          <num4>dwqdqq</num4>
        </skill>
      </skills>
      <armor>wqwq</armor>
      <dps>12</dps>
    </hero>
    <hero id="misho" attack="melee" affiliation="scorge">
      <title>wqq</title>
      <atribute short="AGI" />
      <status>21</status>
      <movespeed>2</movespeed>
      <skills>
        <skill>
          <num1>ewq</num1>
          <num2>dqwdqw</num2>
          <num3>dqwdqw</num3>
          <num4>dwqdqq</num4>
        </skill>
      </skills>
      <armor>wqwq</armor>
      <dps>12</dps>
    </hero>
  </heroes>
  <items>
    <item id="0" slot="1" hero="EarthDick">
      <merchant>merchant</merchant>
      <price>12</price>
      <effects>
        <effect>
          <main>dobre</main>
          <secondary>qko da</secondary>
        </effect>
        <effect>
          <main>dobre</main>
          <secondary>qko da</secondary>
        </effect>
      </effects>
      <need>tes</need>
      <description>description</description>
    </item>
    <item id="0" slot="1" hero="EarthDick">
      <merchant>merchant</merchant>
      <price>12</price>
      <effects>
        <effect>
          <main>dobre</main>
          <secondary>qko da</secondary>
        </effect>
        <effect>
          <main>dobre</main>
          <secondary>qko da</secondary>
        </effect>
      </effects>
      <need>tes</need>
      <description>description</description>
    </item>
  </items>
</dota>

=== mishokopchev/FMI-c-/asp-dota/XML/valid_xml_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dota SYSTEM "dota.dtd">
<dota>
    
    <game>
        <name> Defense of the Ancients ( Дота )</name>
        <genre> Multiplayer online battle arena ( или бойна арена с повече от един играча ) </genre>
        <designer> "Ice Frog" </designer>
    </game>
    
    <buildings>
        <building side="sentinel" main="Tree of Life">
            <region> средата </region>
            <type> кула </type>
            <life> 1100 </life>
            <defence> 2 </defence>
            <damage> 10 </damage>
        </building>
        <building side="scorge" main="Acolyte">
            <region> средата </region>
            <type> кула  </type>
            <life> 2200 </life>
            <defence> 3 </defence>
            <damage> 23 </damage>
        </building>
    </buildings>
    
    <heroes>
        <hero id="Admiral" attack="melee" affiliation="sentinel">
            <title> Daelin Proudmoore </title> 
            <atribute short="STR"> сила </atribute>
            <status> няма </status>
            <movespeed> Скорост на движение: 300 </movespeed>
            <skills>
                <skill>
                    <num1> Torrent   </num1>
                    <num2> Tidebringer   </num2>
                    <num3> X Marks The Spot   </num3>
                    <num4> Ghost Ship  </num4>
                </skill>
            </skills>
            <armor> броня: 1.96 </armor>
            <dps> щета: 50 - 60 </dps>
        </hero>  
        <hero id="Oblivion" attack="range" affiliation="scorge">
            <title> Pugna </title> 
            <atribute short="INT"> интелигентност </atribute>
            <status> няма </status>
            <movespeed> Скорост на движение: 320 </movespeed>
            <skills>
                <skill>
                    <num1> Nether Blast  </num1>
                    <num2> Decrepify  </num2>
                    <num3> Nether Ward  </num3>
                    <num4> Life Drain </num4>
                </skill>
            </skills>
            <armor> броня: 1.54 </armor>
            <dps> щета: 41 - 49 </dps>
        </hero>  
        <hero id="Gorgon" attack="range" affiliation="scorge">
            <title> Medusa </title> 
            <atribute short="AGI"> ловкост  </atribute>
            <status> няма </status>
            <movespeed> Скорост на движение: 290 </movespeed>
            <skills>
                <skill>
                    <num1> Split Shot   </num1>
                    <num2> Mystic Snake  </num2>
                    <num3> Mana Shield   </num3>
                    <num4> Stone Gaze   </num4>
                </skill>
            </skills>
            <armor> броня: 1.8 </armor>
            <dps> щета: 44 - 50 </dps>
        </hero>  
    </heroes>
    
    <items>
        <item id="Quarterstaff" slot="5" hero="Admiral">
            <merchant> Arcane Sanctum </merchant>
            <price> 900 </price>
            <effects> 
                <effect>
                    <main> 10 щета </main>
                    <secondary> 10 скорост на атака</secondary>
                </effect>
            </effects>
            <need> няма </need>
            <description> Четири от тях образуват един обикновен персонал, уф! </description>
        </item>
        <item id="Crystalys" slot="2" hero="Admiral">
            <merchant> Ancient Weaponary </merchant>
            <price> 2150 </price>
            <effects> 
                <effect>
                    <main> 30 щета </main>
                    <secondary> Критичен удар (пасивно) </secondary>
                </effect>
            </effects>
            <need> Меч (1200) , Остриета на атаката (450)  </need>
            <description> Кръстен решителна битка във войната на влъхвите, в който бунтовниците са спасени от Рошан от затвора си в Crystalys. </description>
        </item>
        <item id="Eye of Skadi" slot="1" hero="Gorgon">
            <merchant> Enchanted Artifacts </merchant>
            <price> 5675 </price>
            <effects> 
                <effect>
                    <main> 25 ловкост, 25 сила, 25 интелигентност </main>
                    <secondary> Ледена атака (пасивно, орб) </secondary>
                </effect>
            </effects>
            <need> 2 X последен орб (2100)  </need>
            <description> Изключително рядък артефакт, охраняван от лазурните драконите на Northrend. </description>
        </item>
    </items>
    
</dota>
